version: '3'
services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: node:16
    container_name: trybecash_api
    restart: always
    tty: true
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=trybecashdb
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - "database"
  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trybecashdb
    ports:
      - 3306:3306
    volumes:
      - ./trybecash_script.sql:/docker-entrypoint-initdb.d/trybecash_script.sql
